const colorOptions = [
        {color: "ALICEBLUE", value: "#F0F8FF"},
        {color: "ANTIQUEWHITE", value: "#FAEBD7"},
        {color: "AQUA", value: "#00FFFF"},
        {color: "AQUAMARINE", value: "#7FFFD4"},
        {color: "AZURE", value: "#F0FFFF"},
        {color: "BEIGE", value: "#F5F5DC"},
        {color: "BISQUE", value: "#FFE4C4"},
        {color: "BLACK", value: "#000000"},
        {color: "BLANCHEDALMOND", value: "#FFEBCD"},
        {color: "BLUE", value: "#0000FF"},
        {color: "BLUEVIOLET", value: "#8A2BE2"},
        {color: "BROWN", value: "#A52A2A"},
        {color: "BURLYWOOD", value: "#DEB887"},
        {color: "CADETBLUE", value: "#5F9EA0"},
        {color: "CHARTREUSE", value: "#7FFF00"},
        {color: "CHOCOLATE", value: "#D2691E"},
        {color: "CORAL", value: "#FF7F50"},
        {color: "CORNFLOWERBLUE", value: "#6495ED"},
        {color: "CORNSILK", value: "#FFF8DC"},
        {color: "CRIMSON", value: "#DC143C"},
        {color: "CYAN", value: "#00FFFF"},
        {color: "DARKBLUE", value: "#00008B"},
        {color: "DARKCYAN", value: "#008B8B"},
        {color: "DARKGOLDENROD", value: "#B8860B"},
        {color: "DARKGRAY", value: "#A9A9A9"},
        {color: "DARKGREEN", value: "#006400"},
        {color: "DARKGREY", value: "#A9A9A9"},
        {color: "DARKKHAKI", value: "#BDB76B"},
        {color: "DARKMAGENTA", value: "#8B008B"},
        {color: "DARKOLIVEGREEN", value: "#556B2F"},
        {color: "DARKORANGE", value: "#FF8C00"},
        {color: "DARKORCHID", value: "#9932CC"},
        {color: "DARKRED", value: "#8B0000"},
        {color: "DARKSALMON", value: "#E9967A"},
        {color: "DARKSEAGREEN", value: "#8FBC8F"},
        {color: "DARKSLATEBLUE", value: "#483D8B"},
        {color: "DARKSLATEGRAY", value: "#2F4F4F"},
        {color: "DARKTURQUOISE", value: "#00CED1"},
        {color: "DARKVIOLET", value: "#9400D3"},
        {color: "DEEPPINK", value: "#FF1493"},
        {color: "DEEPSKYBLUE", value: "#00BFFF"},
        {color: "DIMGRAY", value: "#696969"},
        {color: "DODGERBLUE", value: "#1E90FF"},
        {color: "FIREBRICK", value: "#B22222"},
        {color: "FLORALWHITE", value: "#FFFAF0"},
        {color: "FORESTGREEN", value: "#228B22"},
        {color: "FUCHSIA", value: "#FF00FF"},
        {color: "GAINSBORO", value: "#DCDCDC"},
        {color: "GHOSTWHITE", value: "#F8F8FF"},
        {color: "GOLD", value: "#FFD700"},
        {color: "GOLDENROD", value: "#DAA520"},
        {color: "GRAY", value: "#808080"},
        {color: "GREEN", value: "#008000"},
        {color: "GREENYELLOW", value: "#ADFF2F"},
        {color: "GREY", value: "#808080"},
        {color: "HONEYDEW", value: "#F0FFF0"},
        {color: "HOTPINK", value: "#FF69B4"},
        {color: "INDIANRED", value: "#CD5C5C"},
        {color: "INDIGO", value: "#4B0082"},
        {color: "IVORY", value: "#FFFFF0"},
        {color: "KHAKI", value: "#F0E68C"},
        {color: "LAVENDER", value: "#E6E6FA"},
        {color: "LAVENDERBLUSH", value: "#FFF0F5"},
        {color: "LAWNGREEN", value: "#7CFC00"},
        {color: "LEMONCHIFFON", value: "#FFFACD"},
        {color: "LIGHTBLUE", value: "#ADD8E6"},
        {color: "LIGHTCORAL", value: "#F08080"},
        {color: "LIGHTCYAN", value: "#E0FFFF"},
        {color: "LIGHTGOLDENRODYELLOW", value: "#FAFAD2"},
        {color: "LIGHTGRAY", value: "#D3D3D3"},
        {color: "LIGHTGREEN", value: "#90EE90"},
        {color: "LIGHTGREY", value: "#D3D3D3"},
        {color: "LIGHTPINK", value: "#FFB6C1"},
        {color: "LIGHTSEAGREEN", value: "#20B2AA"},
        {color: "LIGHTSKYBLUE", value: "#87CEFA"},
        {color: "LIGHTSLATEGRAY", value: "#778899"},
        {color: "LIGHTSTEELBLUE", value: "#B0C4DE"},
        {color: "LIGHTYELLOW", value: "#FFFFE0"},
        {color: "LIME", value: "#00FF00"},
        {color: "LIMEGREEN", value: "#32CD32"},
        {color: "LINEN", value: "#FAF0E6"},
        {color: "MAGENTA", value: "#FF00FF"},
        {color: "MAROON", value: "#800000"},
        {color: "MEDIUMAQUAMARINE", value: "#66CDAA"},
        {color: "MEDIUMBLUE", value: "#0000CD"},
        {color: "MEDIUMORCHID", value: "#BA55D3"},
        {color: "MEDIUMPURPLE", value: "#9370DB"},
        {color: "MEDIUMSEAGREEN", value: "#3CB371"},
        {color: "MEDIUMSLATEBLUE", value: "#7B68EE"},
        {color: "MEDIUMSPRINGGREEN", value: "#00FA9A"},
        {color: "MEDIUMTURQUOISE", value: "#48D1CC"},
        {color: "MEDIUMVIOLETRED", value: "#C71585"},
        {color: "MIDNIGHTBLUE", value: "#191970"},
        {color: "MINTCREAM", value: "#F5FFFA"},
        {color: "MISTYROSE", value: "#FFE4E1"},
        {color: "MOCCASIN", value: "#FFE4B5"},
        {color: "NAVAJOWHITE", value: "#FFDEAD"},
        {color: "NAVY", value: "#000080"},
        {color: "OLDLACE", value: "#FDF5E6"},
        {color: "OLIVE", value: "#808000"},
        {color: "OLIVEDRAB", value: "#6B8E23"},
        {color: "ORANGE", value: "#FFA500"},
        {color: "ORANGERED", value: "#FF4500"},
        {color: "ORCHID", value: "#DA70D6"},
        {color: "PALEGOLDENROD", value: "#EEE8AA"},
        {color: "PALEGREEN", value: "#98FB98"},
        {color: "PALETURQUOISE", value: "#AFEEEE"},
        {color: "PALEVIOLETRED", value: "#DB7093"},
        {color: "PAPAYAWHIP", value: "#FFEFD5"},
        {color: "PEACHPUFF", value: "#FFDAB9"},
        {color: "PERU", value: "#CD853F"},
        {color: "PINK", value: "#FFC0CB"},
        {color: "PLUM", value: "#DDA0DD"},
        {color: "POWDERBLUE", value: "#B0E0E6"},
        {color: "PURPLE", value: "#800080"},
        {color: "RED", value: "#FF0000"},
        {color: "ROSYBROWN", value: "#BC8F8F"},
        {color: "ROYALBLUE", value: "#4169E1"},
        {color: "SADDLEBROWN", value: "#8B4513"},
        {color: "SALMON", value: "#FA8072"},
        {color: "SANDYBROWN", value: "#F4A460"},
        {color: "SEAGREEN", value: "#2E8B57"},
        {color: "SEASHELL", value: "#FFF5EE"},
        {color: "SIENNA", value: "#A0522D"},
        {color: "SILVER", value: "#C0C0C0"},
        {color: "SKYBLUE", value: "#87CEEB"},
        {color: "SLATEBLUE", value: "#6A5ACD"},
        {color: "SLATEGRAY", value: "#708090"},
        {color: "SNOW", value: "#FFFAFA"},
        {color: "SPRINGGREEN", value: "#00FF7F"},
        {color: "STEELBLUE", value: "#4682B4"},
        {color: "TAN", value: "#D2B48C"},
        {color: "TEAL", value: "#008080"},
        {color: "THISTLE", value: "#D8BFD8"},
        {color: "TOMATO", value: "#FF6347"},
        {color: "TURQUOISE", value: "#40E0D0"},
        {color: "VIOLET", value: "#EE82EE"},
        {color: "WHEAT", value: "#F5DEB3"},
        {color: "WHITE", value: "#FFFFFF"},
        {color: "WHITESMOKE", value: "#F5F5F5"},
        {color: "YELLOW", value: "#FFFF00"},
        {color: "YELLOWGREEN", value: "#9ACD32"}
    ],
    transparencyOptions = [
        {caption: "0 %", value: 1.0},
        {caption: "10 %", value: 0.9},
        {caption: "20 %", value: 0.8},
        {caption: "30 %", value: 0.7},
        {caption: "40 %", value: 0.6},
        {caption: "50 %", value: 0.5},
        {caption: "60 %", value: 0.4},
        {caption: "70 %", value: 0.3},
        {caption: "80 %", value: 0.2},
        {caption: "90 %", value: 0.1},
        {caption: "100 %", value: 0.0}
    ];

export {
    colorOptions,
    transparencyOptions
};
